blank_issues_enabled: true
contact_links:
  - name: Latest StreamHub Deck release
    url: https://github.com/filipedeptulski/StreamHub-Deck/releases/latest
    about: Download the latest SteamOS package.
